---
title: "Oman Dataset"
output: html_notebook
---

Data summary for Oman data within Padme Arabia

Tasks to do: 

Field Records
Herbarium Records

Summarise both - 
number of records - field; herbarium; (literature) 
numbers of is.na for key fields author, location, determination, collection number



0) 
Chop out the Oman data
Geog.Location contains or is: Oman

1 - Category data:
a) Authors
b) Locations
c) NULLs

2 - Continuous data: 
a) Points in sea
b) Points N but not E /vice versa
c) NULLs

3 - Misc:
a) Duplication of records (not specimen duplicates K, E, etc)


How to begin these tasks: 

1a) 
in R: 
table(~collector), with numbers
then assess the list

Export & OPENREFINE
Cluster groups, export from Openrefine then re-import to R later




```{r}
print("test")
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
